/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import DAO.Loai_DAO;
import DAO.MonAn_DAO;
import Entity.Loai;
import Entity.MonAn;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.sql.SQLException;
import java.text.Normalizer;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Pattern;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JViewport;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.JTextComponent;

/**
 *
 * @author ADMIN
 */
public class QLMAForm extends javax.swing.JPanel {

    private final MonAn_DAO monAn_dao;
    private DefaultTableModel modelTable;
    private final Loai_DAO loaiMonAn_dao;

    /**
     * Creates new form QLMAForm
     */
    public QLMAForm() {
        initComponents();
        try {
            ConnectDB.ConnectDB.getInstance().connect();
            System.out.println("Connected!!");
        } catch (SQLException e) {
            e.printStackTrace();
        }
        monAn_dao = new MonAn_DAO();
        loaiMonAn_dao = new Loai_DAO();

        docDuLieuDatabaseVaoTable();
        docDuLieuDatabaseVaoCbo();
        UIManager.put("ComboBox.disabledForeground", Color.BLACK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        timKiemDialog = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        timTheoMa = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        timTheoTen = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        timTheoLoaiMon = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        loaiMonAnCbo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        soLuongTxt = new javax.swing.JTextField();
        donGiaTxt = new javax.swing.JTextField();
        tenMonAnTxt = new javax.swing.JTextField();
        trangThaiCbo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        maMonAnTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        scrollPaneWin111 = new Utils.scroll.win11.ScrollPaneWin11();
        String[] colHeader = {"Mã món ăn", "Tên món ăn", "Đơn giá", "Số lượng", "Trạng thái", "Mã loại"};
        modelTable = new DefaultTableModel(colHeader, 0) {
            /**
            *
            */
            private static final long serialVersionUID = 1L;

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        jTable2 = new javax.swing.JTable(modelTable);
        pictureBox1 = new Utils.Swing.PictureBox();

        jDialog1.setModal(true);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Bạn có muốn chọn ảnh cho món ăn không?");

        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton5.setText("Không");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton6.setText("Có");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addGap(50, 50, 50)
                        .addComponent(jButton6)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        timKiemDialog.setModal(true);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Hãy chọn phương thức tìm kiếm");

        jButton11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton11.setText("Tìm theo mã món ăn");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton12.setText("Tìm theo tên món ăn");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton13.setText("Tìm theo loại món");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setBackground(new java.awt.Color(255, 0, 51));
        jButton14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton14.setText("Hủy");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout timKiemDialogLayout = new javax.swing.GroupLayout(timKiemDialog.getContentPane());
        timKiemDialog.getContentPane().setLayout(timKiemDialogLayout);
        timKiemDialogLayout.setHorizontalGroup(
            timKiemDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timKiemDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(timKiemDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        timKiemDialogLayout.setVerticalGroup(
            timKiemDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timKiemDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jButton11)
                .addGap(18, 18, 18)
                .addComponent(jButton12)
                .addGap(18, 18, 18)
                .addComponent(jButton13)
                .addGap(18, 18, 18)
                .addComponent(jButton14)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Nhập mã món ăn");

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jButton7.setBackground(new java.awt.Color(51, 204, 0));
        jButton7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton7.setText("Tìm");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton15.setBackground(new java.awt.Color(255, 0, 51));
        jButton15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton15.setText("Hủy");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout timTheoMaLayout = new javax.swing.GroupLayout(timTheoMa.getContentPane());
        timTheoMa.getContentPane().setLayout(timTheoMaLayout);
        timTheoMaLayout.setHorizontalGroup(
            timTheoMaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timTheoMaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(timTheoMaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(jTextField1)
                    .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        timTheoMaLayout.setVerticalGroup(
            timTheoMaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timTheoMaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jButton15)
                .addContainerGap())
        );

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Nhập tên món ăn");

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jButton8.setBackground(new java.awt.Color(51, 204, 0));
        jButton8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton8.setText("Tìm");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton16.setBackground(new java.awt.Color(255, 0, 51));
        jButton16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton16.setText("Hủy");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout timTheoTenLayout = new javax.swing.GroupLayout(timTheoTen.getContentPane());
        timTheoTen.getContentPane().setLayout(timTheoTenLayout);
        timTheoTenLayout.setHorizontalGroup(
            timTheoTenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timTheoTenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(timTheoTenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(jTextField2)
                    .addComponent(jButton16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        timTheoTenLayout.setVerticalGroup(
            timTheoTenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timTheoTenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jButton16)
                .addContainerGap())
        );

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Chọn loại món muốn tìm");

        jButton9.setBackground(new java.awt.Color(51, 204, 0));
        jButton9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton9.setText("Tìm");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton17.setBackground(new java.awt.Color(255, 0, 51));
        jButton17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton17.setText("Hủy");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout timTheoLoaiMonLayout = new javax.swing.GroupLayout(timTheoLoaiMon.getContentPane());
        timTheoLoaiMon.getContentPane().setLayout(timTheoLoaiMonLayout);
        timTheoLoaiMonLayout.setHorizontalGroup(
            timTheoLoaiMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timTheoLoaiMonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(timTheoLoaiMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        timTheoLoaiMonLayout.setVerticalGroup(
            timTheoLoaiMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timTheoLoaiMonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton17)
                .addContainerGap())
        );

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/adding.png"))); // NOI18N
        jButton2.setText("Thêm món");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/upgrade.png"))); // NOI18N
        jButton1.setText("Cập nhật");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/refresh.png"))); // NOI18N
        jButton3.setText("Làm mới");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/loupe.png"))); // NOI18N
        jButton4.setText("Tìm");
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11))
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel5.setText("Loại món ăn");

        loaiMonAnCbo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        loaiMonAnCbo.setEnabled(false);
        loaiMonAnCbo.setRenderer(new DefaultListCellRenderer() {
            @Override
            public void paint(Graphics g) {
                setForeground(Color.BLACK);
                super.paint(g);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel3.setText("Đơn giá");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel1.setText("Mã món ăn");

        soLuongTxt.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        soLuongTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soLuongTxtActionPerformed(evt);
            }
        });

        donGiaTxt.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        donGiaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donGiaTxtActionPerformed(evt);
            }
        });

        tenMonAnTxt.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tenMonAnTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tenMonAnTxt.setEnabled(false);
        tenMonAnTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenMonAnTxtActionPerformed(evt);
            }
        });

        trangThaiCbo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        trangThaiCbo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Còn hàng", "Hết hàng" }));
        trangThaiCbo.setEnabled(false);
        trangThaiCbo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trangThaiCboActionPerformed(evt);
            }
        });
        trangThaiCbo.setRenderer(new DefaultListCellRenderer() {
            @Override
            public void paint(Graphics g) {
                setForeground(Color.BLACK);
                super.paint(g);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel6.setText("Trạng thái");

        maMonAnTxt.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        maMonAnTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        maMonAnTxt.setEnabled(false);
        maMonAnTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maMonAnTxtActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel2.setText("Tên món ăn");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel4.setText("Số lượng");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tenMonAnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(donGiaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maMonAnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(soLuongTxt)
                    .addComponent(loaiMonAnCbo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(trangThaiCbo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(maMonAnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soLuongTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(tenMonAnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loaiMonAnCbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(donGiaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(trangThaiCbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 25, Short.MAX_VALUE))
        );

        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        scrollPaneWin111.setViewportView(jTable2);
        scrollPaneWin111.setColumnHeader(new JViewport() {
            /**
            *
            */
            private static final long serialVersionUID = 1L;

            @Override
            public Dimension getPreferredSize() {
                Dimension d = super.getPreferredSize();
                d.height = 32;
                return d;
            }
        });
        jTable2.getTableHeader().setResizingAllowed(false);
        jTable2.getTableHeader().setReorderingAllowed(false);
        jTable2.setFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 15));
        jTable2.setRowHeight(jTable2.getRowHeight() + 10);

        pictureBox1.setImage(new javax.swing.ImageIcon(getClass().getResource("/ImageOfFood/nothing.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrollPaneWin111, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pictureBox1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pictureBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneWin111, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void trangThaiCboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trangThaiCboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trangThaiCboActionPerformed

    private void soLuongTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soLuongTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soLuongTxtActionPerformed

    private void maMonAnTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maMonAnTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maMonAnTxtActionPerformed

    private void donGiaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donGiaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_donGiaTxtActionPerformed

    private void tenMonAnTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenMonAnTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tenMonAnTxtActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        tenMonAnTxt.setEnabled(false);
        loaiMonAnCbo.setEnabled(false);
        List<Loai> listL = loaiMonAn_dao.getAllTableLoaiMon();
        List<MonAn> listMA = monAn_dao.getAllTableMonAn();
        String tenLoai = null;
        String pictureName = null;
        int row = jTable2.getSelectedRow();

        if (row >= 0) {
            maMonAnTxt.setText((String) modelTable.getValueAt(row, 0));
            tenMonAnTxt.setText((String) modelTable.getValueAt(row, 1));
            donGiaTxt.setText((String) modelTable.getValueAt(row, 2));
            soLuongTxt.setText((String) modelTable.getValueAt(row, 3));
            trangThaiCbo.setSelectedItem((String) modelTable.getValueAt(row, 4));

            for (Loai loai : listL) {
                if (modelTable.getValueAt(row, 5).equals(loai.getMaLoai())) {
                    tenLoai = loai.getTenLoai();
                    break;
                }
            }
            loaiMonAnCbo.setSelectedItem(tenLoai);

            // Kiểm tra mã món ăn và set hình ảnh
            for (MonAn ma : listMA) {
                if (modelTable.getValueAt(row, 0).equals(ma.getMaMA())) {
                    pictureName = ma.getImageName();
                    break; // Không cần tiếp tục nếu đã tìm thấy món ăn
                }
            }
            if (pictureName != null) {
                pictureBox1.setImage(new javax.swing.ImageIcon(getClass().getResource("/ImageOfFood/" + pictureName)));
                pictureBox1.repaint();
                pictureBox1.revalidate();
            }
        }
        loaiMonAnCbo.setRenderer(new DefaultListCellRenderer() {
            @Override
            public void paint(Graphics g) {
                setForeground(Color.BLACK);
                super.paint(g);
            }
        });
        trangThaiCbo.setRenderer(new DefaultListCellRenderer() {
            @Override
            public void paint(Graphics g) {
                setForeground(Color.BLACK);
                super.paint(g);
            }
        });
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        modelTable.setRowCount(0);
        maMonAnTxt.setText("");
        tenMonAnTxt.setText("");
        donGiaTxt.setText("");
        soLuongTxt.setText("");
        loaiMonAnCbo.setSelectedIndex(0);
        trangThaiCbo.setSelectedIndex(0);
        pictureBox1.setImage(new javax.swing.ImageIcon(getClass().getResource("/ImageOfFood/nothing.png")));
        pictureBox1.repaint();
        pictureBox1.revalidate();
        tenMonAnTxt.setEnabled(true);
        loaiMonAnCbo.setEnabled(true);
        jTable2.clearSelection();
        docDuLieuDatabaseVaoTable();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        List<Loai> listL = loaiMonAn_dao.getAllTableLoaiMon();
        int row = jTable2.getSelectedRow();
        if (row >= 0) {
            modelTable.setValueAt(donGiaTxt.getText(), row, 2);
            modelTable.setValueAt(soLuongTxt.getText(), row, 3);
            if (soLuongTxt.getText().equals("0")) {
                trangThaiCbo.setSelectedIndex(1);
            } else {
                trangThaiCbo.setSelectedIndex(0);
            }
            modelTable.setValueAt(trangThaiCbo.getSelectedItem(), row, 4);

            String maMA = maMonAnTxt.getText();
            String tenMA = tenMonAnTxt.getText();
            float donGia = Float.parseFloat(donGiaTxt.getText());
            int soLuong = Integer.parseInt(soLuongTxt.getText());
            String maLoai = null;
            String tenLoai = null;
            String trangThai = (String) trangThaiCbo.getSelectedItem();
            String imageName = "";

            Loai loai = new Loai(maLoai, tenLoai);
            MonAn ma = new MonAn(maMA, tenMA, donGia, soLuong, trangThai, loai, imageName);
            if (monAn_dao.update(ma)) {
                JOptionPane.showMessageDialog(null, "Cập nhật thành công");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    private static boolean isAddingImage = false;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (tenMonAnTxt.isEnabled()) {
            if (tenMonAnTxt.getText().trim().isEmpty() || donGiaTxt.getText().trim().isEmpty() || soLuongTxt.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ");
            } else {
                jDialog1.setSize(403, 130);
                jDialog1.setLocationRelativeTo(null);
                jDialog1.setVisible(true);
                if (isAddingImage == false) {
                    String tenMA = tenMonAnTxt.getText();
                    float donGia = Float.parseFloat(donGiaTxt.getText());
                    int soLuong = Integer.parseInt(soLuongTxt.getText());
                    String trangThai = (String) trangThaiCbo.getSelectedItem();
                    String tenLoai = (String) loaiMonAnCbo.getSelectedItem();
                    List<Loai> listL = loaiMonAn_dao.getAllTableLoaiMon();
                    String maLoai = null;
                    for (Loai loai : listL) {
                        if (tenLoai.equals(loai.getTenLoai())) {
                            maLoai = loai.getMaLoai();
                            break;
                        }
                    }
                    Loai loai = new Loai(maLoai, tenLoai);
                    int total = jTable2.getRowCount();
                    total += 1;

                    String maMa = "MA" + maLoai.substring(1) + String.format("%03d", total);
                    MonAn ma = new MonAn(maMa, tenMA, donGia, soLuong, trangThai, loai, null);
                    if (monAn_dao.insert(ma)) {
                        JOptionPane.showMessageDialog(null, "Thêm món ăn thành công");
                        modelTable.setRowCount(0);
                        maMonAnTxt.setText("");
                        tenMonAnTxt.setText("");
                        donGiaTxt.setText("");
                        soLuongTxt.setText("");
                        loaiMonAnCbo.setSelectedIndex(0);
                        trangThaiCbo.setSelectedIndex(0);
                        pictureBox1.setImage(new javax.swing.ImageIcon(getClass().getResource("/ImageOfFood/nothing.png")));
                        pictureBox1.repaint();
                        pictureBox1.revalidate();
                        tenMonAnTxt.setEnabled(true);
                        loaiMonAnCbo.setEnabled(true);
                        jTable2.clearSelection();
                        docDuLieuDatabaseVaoTable();
                    }
                } else {
                    String tenMonAn = tenMonAnTxt.getText();
                    JFileChooser fileChooser = new JFileChooser();
                    fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Image files", "jpg", "png"));
                    fileChooser.setMultiSelectionEnabled(false);
                    int returnValue = fileChooser.showDialog(this, "Chọn hình ảnh");
                    String newFileName = null;
                    if (returnValue == fileChooser.APPROVE_OPTION) {
                        File f = fileChooser.getSelectedFile();
                        System.out.println("Selected file: " + f.getAbsolutePath());

                        String normalizedTenMonAn = removeVietnameseAccents(tenMonAn).replaceAll(" ", "").toLowerCase();
                        String fileExtension = getFileExtension(f);
                        newFileName = normalizedTenMonAn + "." + fileExtension;
                        String projectDir = System.getProperty("user.dir"); // Lấy đường dẫn thư mục project
                        File destFolder = new File(projectDir + File.separator + "src" + File.separator + "ImageOfFood");
                        File destFile = new File(destFolder, newFileName);
                        try {
                            Files.copy(f.toPath(), destFile.toPath(), StandardCopyOption.REPLACE_EXISTING);
                        } catch (IOException e) {
                            e.printStackTrace();
                            JOptionPane.showMessageDialog(null, "Không thể sử dụng hình ảnh này. Hãy kiểm tra lại đường dẫn!");
                            return;
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Đã hủy thêm món");
                        return;
                    }
                    String tenMA = tenMonAnTxt.getText();
                    float donGia = Float.parseFloat(donGiaTxt.getText());
                    int soLuong = Integer.parseInt(soLuongTxt.getText());
                    String trangThai = (String) trangThaiCbo.getSelectedItem();
                    String tenLoai = (String) loaiMonAnCbo.getSelectedItem();
                    List<Loai> listL = loaiMonAn_dao.getAllTableLoaiMon();
                    String maLoai = null;
                    for (Loai loai : listL) {
                        if (tenLoai.equals(loai.getTenLoai())) {
                            maLoai = loai.getMaLoai();
                            break;
                        }
                    }
                    Loai loai = new Loai(maLoai, tenLoai);
                    int total = jTable2.getRowCount();
                    total += 1;

                    String maMa = "MA" + maLoai.substring(1) + String.format("%03d", total);
                    MonAn ma = new MonAn(maMa, tenMA, donGia, soLuong, trangThai, loai, newFileName);
                    if (monAn_dao.insert(ma)) {
                        JOptionPane.showMessageDialog(null, "Thêm món ăn thành công");
                        modelTable.setRowCount(0);
                        maMonAnTxt.setText("");
                        tenMonAnTxt.setText("");
                        donGiaTxt.setText("");
                        soLuongTxt.setText("");
                        loaiMonAnCbo.setSelectedIndex(0);
                        trangThaiCbo.setSelectedIndex(0);
                        pictureBox1.setImage(new javax.swing.ImageIcon(getClass().getResource("/ImageOfFood/nothing.png")));
                        pictureBox1.repaint();
                        pictureBox1.revalidate();
                        jTable2.clearSelection();
                        docDuLieuDatabaseVaoTable();
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Làm mới trước khi thêm món");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        isAddingImage = true;
        jDialog1.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        isAddingImage = false;
        jDialog1.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        tenMonAnTxt.setEnabled(false);
        loaiMonAnCbo.setEnabled(false);
        loaiMonAnCbo.setRenderer(new DefaultListCellRenderer() {
            @Override
            public void paint(Graphics g) {
                setForeground(Color.BLACK);
                super.paint(g);
            }
        });
        trangThaiCbo.setRenderer(new DefaultListCellRenderer() {
            @Override
            public void paint(Graphics g) {
                setForeground(Color.BLACK);
                super.paint(g);
            }
        });
        timKiemDialog.setSize(400, 300);
        timKiemDialog.setLocationRelativeTo(null);
        timKiemDialog.setVisible(true);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        timKiemDialog.dispose();
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        timKiemDialog.dispose();
        timTheoMa.setSize(182, 230);
        timTheoMa.setLocationRelativeTo(null);
        timTheoMa.setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        timTheoMa.dispose();
        timKiemDialog.setVisible(true);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String ma = jTextField1.getText().trim();
        if (!ma.isEmpty()) {
            ArrayList<MonAn> mon = monAn_dao.searchTheoMa(ma);
            modelTable.setRowCount(0);
            for (MonAn monA : mon) {
                modelTable.addRow(new Object[]{monA.getMaMA(), monA.getTenMA(), String.valueOf(monA.getDonGia()), String.valueOf(monA.getSoLuong()), monA.getTrangThai(), monA.getMaLoai().getMaLoai()});
            }
            maMonAnTxt.setText("");
            tenMonAnTxt.setText("");
            donGiaTxt.setText("");
            soLuongTxt.setText("");
            loaiMonAnCbo.setSelectedIndex(0);
            trangThaiCbo.setSelectedIndex(0);
            pictureBox1.setImage(new javax.swing.ImageIcon(getClass().getResource("/ImageOfFood/nothing.png")));
            pictureBox1.repaint();
            pictureBox1.revalidate();
            jTable2.clearSelection();
            jTextField1.setText("");
            timTheoMa.dispose();
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String ten = jTextField2.getText().trim();
        if (!ten.isEmpty()) {
            ArrayList<MonAn> mon = monAn_dao.searchTheoTen(ten);
            modelTable.setRowCount(0);
            for (MonAn monA : mon) {
                modelTable.addRow(new Object[]{monA.getMaMA(), monA.getTenMA(), String.valueOf(monA.getDonGia()), String.valueOf(monA.getSoLuong()), monA.getTrangThai(), monA.getMaLoai().getMaLoai()});
            }
            maMonAnTxt.setText("");
            tenMonAnTxt.setText("");
            donGiaTxt.setText("");
            soLuongTxt.setText("");
            loaiMonAnCbo.setSelectedIndex(0);
            trangThaiCbo.setSelectedIndex(0);
            pictureBox1.setImage(new javax.swing.ImageIcon(getClass().getResource("/ImageOfFood/nothing.png")));
            pictureBox1.repaint();
            pictureBox1.revalidate();
            jTable2.clearSelection();
            jTextField2.setText("");
            timTheoTen.dispose();
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        timTheoTen.dispose();
        timKiemDialog.setVisible(true);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        timKiemDialog.dispose();
        timTheoTen.setSize(182, 230);
        timTheoTen.setLocationRelativeTo(null);
        timTheoTen.setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String maLoai = (String) jComboBox1.getSelectedItem();
        if (!maLoai.isEmpty()) {
            List<Loai> listL = loaiMonAn_dao.getAllTableLoaiMon();
            for (Loai loai : listL) {
                if (loai.getTenLoai().equals(maLoai)) {
                    maLoai = loai.getMaLoai();
                    break;
                }
            }
            ArrayList<MonAn> mon = monAn_dao.searchTheoLoaiMon(maLoai);
            modelTable.setRowCount(0);
            for (MonAn monA : mon) {
                modelTable.addRow(new Object[]{monA.getMaMA(), monA.getTenMA(), String.valueOf(monA.getDonGia()), String.valueOf(monA.getSoLuong()), monA.getTrangThai(), monA.getMaLoai().getMaLoai()});
            }
            maMonAnTxt.setText("");
            tenMonAnTxt.setText("");
            donGiaTxt.setText("");
            soLuongTxt.setText("");
            loaiMonAnCbo.setSelectedIndex(0);
            trangThaiCbo.setSelectedIndex(0);
            pictureBox1.setImage(new javax.swing.ImageIcon(getClass().getResource("/ImageOfFood/nothing.png")));
            pictureBox1.repaint();
            pictureBox1.revalidate();
            jTable2.clearSelection();
            jComboBox1.setSelectedIndex(0);
            timTheoLoaiMon.dispose();
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        timTheoLoaiMon.dispose();
        timKiemDialog.setVisible(true);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        timKiemDialog.dispose();
        timTheoLoaiMon.setSize(235, 230);
        timTheoLoaiMon.setLocationRelativeTo(null);
        timTheoLoaiMon.setVisible(true);
    }//GEN-LAST:event_jButton13ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField donGiaTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JComboBox<String> loaiMonAnCbo;
    private javax.swing.JTextField maMonAnTxt;
    private Utils.Swing.PictureBox pictureBox1;
    private Utils.scroll.win11.ScrollPaneWin11 scrollPaneWin111;
    private javax.swing.JTextField soLuongTxt;
    private javax.swing.JTextField tenMonAnTxt;
    private javax.swing.JDialog timKiemDialog;
    private javax.swing.JDialog timTheoLoaiMon;
    private javax.swing.JDialog timTheoMa;
    private javax.swing.JDialog timTheoTen;
    private javax.swing.JComboBox<String> trangThaiCbo;
    // End of variables declaration//GEN-END:variables

    private void docDuLieuDatabaseVaoTable() {
        List<MonAn> list = monAn_dao.getAllTableMonAn();
        for (MonAn ma : list) {
            modelTable.addRow(new Object[]{ma.getMaMA(), ma.getTenMA(), String.valueOf(ma.getDonGia()), String.valueOf(ma.getSoLuong()), ma.getTrangThai(), ma.getMaLoai().getMaLoai()});
        }
    }

    private void docDuLieuDatabaseVaoCbo() {
        List<Loai> list = loaiMonAn_dao.getAllTableLoaiMon();
        for (Loai loai : list) {
            loaiMonAnCbo.addItem(loai.getTenLoai());
            jComboBox1.addItem(loai.getTenLoai());
        }
    }

    public static String removeVietnameseAccents(String str) {
        String normalized = Normalizer.normalize(str, Normalizer.Form.NFD);
        Pattern pattern = Pattern.compile("\\p{InCombiningDiacriticalMarks}+");
        return pattern.matcher(normalized).replaceAll("").replace("đ", "d").replace("Đ", "D");
    }

    public static String getFileExtension(File file) {
        String fileName = file.getName();
        int lastIndexOfDot = fileName.lastIndexOf('.');
        return (lastIndexOfDot == -1) ? "" : fileName.substring(lastIndexOfDot + 1).toLowerCase();
    }
}
